version: '3.8'

services:
  # Aplikasi Web (Portal Kelulusan)
  web:
    build: .
    ports:
      - "5180:5000"
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=mansaba_secret
      - DB_NAME=kelulusan
      - PORT=5000
    depends_on:
      - db
    restart: always

  # Database MySQL
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=mansaba_secret
      - MYSQL_DATABASE=kelulusan
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3307:3306" # Port luar 3307 agar tidak bentrok dengan MySQL aaPanel

volumes:
  mysql_data:
